package lawismm02en;

import cpw.mods.fml.common.ModMetadata;


/*
 * mcmod.infoと同様の内容。
 * modの情報を登録するためのクラス。
 *
 * preInitで最初に呼び出す。
 */
public class EnInfoCore {
	public static void registerInfo(ModMetadata meta) {
		meta.modId = EndersNightmare.MOD_ID;
		meta.name = EndersNightmare.MOD_NAME;
		meta.description = "Enders' Nightmare";
		meta.version = EndersNightmare.MOD_VERSION;
		meta.url = "http://lawiss.com/minecraft-modding/";
		meta.authorList.add("Lawillia");
		meta.credits = "";
		meta.logoFile = "";
		meta.autogenerated = false;
	}
}
