package lawismm01dbm.config;

import cpw.mods.fml.common.ModMetadata;
import lawismm01dbm.DisposableBedMod;


/*
 * mcmod.infoと同様の内容。
 * modの情報を登録するためのクラス。
 *
 * preInitで最初に呼び出す。
 */
public class DbmInfoCore {
	public static void registerInfo(ModMetadata meta) {
		meta.modId = DisposableBedMod.MOD_ID;
		meta.name = DisposableBedMod.MOD_NAME;
		meta.description = "Disposable Bed Mod";
		meta.version = DisposableBedMod.MOD_VERSION;
		meta.url = "http://lawiss.com/minecraft-modding/";
		meta.authorList.add("Lawillia");
		meta.credits = "";
		meta.logoFile = "";
		meta.autogenerated = false;
	}
}
