package lawismm03.config;

import cpw.mods.fml.common.ModMetadata;
import lawismm03.LogResetForDQRHC;


/*
 * mcmod.infoと同様の内容。
 * modの情報を登録するためのクラス。
 *
 * preInitで最初に呼び出す。
 */
public class LrdInfoCore {
	public static void registerInfo(ModMetadata meta) {
		meta.modId = LogResetForDQRHC.MOD_ID;
		meta.name = LogResetForDQRHC.MOD_NAME;
		meta.description = LogResetForDQRHC.DESCRIPTION;
		meta.version = LogResetForDQRHC.MOD_VERSION;
		meta.url = "http://lawiss.com/minecraft-modding/";
		meta.authorList.add("Lawillia");
		meta.credits = "";
		meta.logoFile = "";
		meta.autogenerated = false;
	}
}
