package lawismm04;

import cpw.mods.fml.common.ModMetadata;


/*
 * mcmod.infoと同様の内容。
 * modの情報を登録するためのクラス。
 *
 * preInitで最初に呼び出す。
 */
public class PpInfoCore {
	public static void registerInfo(ModMetadata meta) {
		meta.modId = PowerlessPlayer.MOD_ID;
		meta.name = PowerlessPlayer.MOD_NAME;
		meta.description = PowerlessPlayer.DESCRIPTION;
		meta.version = PowerlessPlayer.MOD_VERSION;
		meta.url = "http://lawiss.com/minecraft-modding/";
		meta.authorList.add("Lawillia");
		meta.credits = "";
		meta.logoFile = "";
		meta.autogenerated = false;
	}
}
